// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8YftZcy3niQY1Yzd11AxGs3iLWGLkMCo',
    appId: '1:471181083835:ios:80cc2e4ef15ab3e05e159e',
    messagingSenderId: '471181083835',
    projectId: 'smart-complaint-box-4adec',
    storageBucket: 'smart-complaint-box-4adec.firebasestorage.app',
    iosBundleId: 'com.example.smartComplaintBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8YftZcy3niQY1Yzd11AxGs3iLWGLkMCo',
    appId: '1:471181083835:ios:80cc2e4ef15ab3e05e159e',
    messagingSenderId: '471181083835',
    projectId: 'smart-complaint-box-4adec',
    storageBucket: 'smart-complaint-box-4adec.firebasestorage.app',
    iosBundleId: 'com.example.smartComplaintBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDDtIGkTnsGvzb28qsGBus4s66BXUhC9s',
    appId: '1:471181083835:web:7b96023f2d2c43b05e159e',
    messagingSenderId: '471181083835',
    projectId: 'smart-complaint-box-4adec',
    authDomain: 'smart-complaint-box-4adec.firebaseapp.com',
    storageBucket: 'smart-complaint-box-4adec.firebasestorage.app',
    measurementId: 'G-FPJE3LNJGF',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDDtIGkTnsGvzb28qsGBus4s66BXUhC9s',
    appId: '1:471181083835:web:7b96023f2d2c43b05e159e',
    messagingSenderId: '471181083835',
    projectId: 'smart-complaint-box-4adec',
    authDomain: 'smart-complaint-box-4adec.firebaseapp.com',
    storageBucket: 'smart-complaint-box-4adec.firebasestorage.app',
    measurementId: 'G-FPJE3LNJGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXdtxi7ppTS9vhy_eviaPEyta5GoWOky8',
    appId: '1:471181083835:android:df2be14f4918b9955e159e',
    messagingSenderId: '471181083835',
    projectId: 'smart-complaint-box-4adec',
    storageBucket: 'smart-complaint-box-4adec.firebasestorage.app',
  );

}